-- =====================================================
-- PHASE 2: CORE DATA MODEL - SIMPLIFIED
-- Global Supply Chain Spoilage Forecasting Project
-- =====================================================

USE DATABASE GLOBAL_SPOILAGE_DB;
USE SCHEMA CORE;

-- 1. Create DATE_SPINE table for continuous time series
CREATE OR REPLACE TABLE CORE.DATE_SPINE (
    DATE_COL DATE PRIMARY KEY,
    YEAR INT,
    MONTH INT,
    QUARTER INT,
    DAY_OF_WEEK INT,
    DAY_OF_MONTH INT,
    WEEK_OF_YEAR INT,
    MONTH_NAME VARCHAR(10),
    QUARTER_NAME VARCHAR(2),
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN
);

-- Populate DATE_SPINE from 1990 to 2025
INSERT INTO CORE.DATE_SPINE (DATE_COL, YEAR, MONTH, QUARTER, DAY_OF_WEEK, DAY_OF_MONTH, WEEK_OF_YEAR, MONTH_NAME, QUARTER_NAME, IS_WEEKEND)
SELECT
    DATEADD(month, SEQ4(), '1990-01-01')::DATE AS DATE_COL,
    YEAR(DATE_COL) AS YEAR,
    MONTH(DATE_COL) AS MONTH,
    QUARTER(DATE_COL) AS QUARTER,
    DAYOFWEEKISO(DATE_COL) AS DAY_OF_WEEK,
    DAYOFMONTH(DATE_COL) AS DAY_OF_MONTH,
    WEEKOFYEAR(DATE_COL) AS WEEK_OF_YEAR,
    MONTHNAME(DATE_COL) AS MONTH_NAME,
    'Q' || QUARTER(DATE_COL) AS QUARTER_NAME,
    CASE WHEN DAYOFWEEKISO(DATE_COL) IN (6, 7) THEN TRUE ELSE FALSE END AS IS_WEEKEND
FROM TABLE(GENERATOR(ROWCOUNT => 432))
ORDER BY DATE_COL;

-- 2. Create ECONOMIC_INDICATORS table
CREATE OR REPLACE TABLE CORE.ECONOMIC_INDICATORS (
    DATE_COL DATE,
    FEDFUNDS_RATE FLOAT,
    RETAIL_SALES FLOAT,
    TREASURY_10Y_RATE FLOAT,
    POPULATION FLOAT,
    CPI FLOAT,
    UNEMPLOYMENT_RATE FLOAT,
    PRIMARY KEY (DATE_COL)
);

-- Populate ECONOMIC_INDICATORS from RAW data
INSERT INTO CORE.ECONOMIC_INDICATORS (DATE_COL, FEDFUNDS_RATE, RETAIL_SALES, TREASURY_10Y_RATE)
SELECT
    TO_DATE(ff.COL1, 'YYYY-MM-DD') AS DATE_COL,
    ff.COL4::FLOAT AS FEDFUNDS_RATE,
    rs.COL2::FLOAT AS RETAIL_SALES,
    t10y.COL4::FLOAT AS TREASURY_10Y_RATE
FROM RAW.FEDFUNDS_DFF ff
JOIN RAW.RETAIL_SALES rs ON TO_DATE(ff.COL1, 'YYYY-MM-DD') = TO_DATE(rs.COL1, 'MM/DD/YYYY')
JOIN RAW.TREASURY_10Y t10y ON TO_DATE(ff.COL1, 'YYYY-MM-DD') = TO_DATE(t10y.COL1, 'YYYY-MM-DD');

-- 3. Create COUNTRY_DATA table
CREATE OR REPLACE TABLE CORE.COUNTRY_DATA (
    COUNTRY_ISO VARCHAR(10),
    COUNTRY_NAME VARCHAR(255),
    REGION VARCHAR(255),
    INCOME_GROUP VARCHAR(255),
    PRIMARY KEY (COUNTRY_ISO)
);

-- Populate COUNTRY_DATA from RAW.WORLD_BANK_DATA
INSERT INTO CORE.COUNTRY_DATA (COUNTRY_ISO, COUNTRY_NAME, REGION)
SELECT DISTINCT
    SUBSTRING(COL1, 1, 10) AS COUNTRY_ISO,
    COL3 AS COUNTRY_NAME,
    COL2 AS REGION
FROM RAW.WORLD_BANK_DATA
WHERE COL1 IS NOT NULL AND COL3 IS NOT NULL
  AND LENGTH(COL1) <= 10;

-- 4. Create UNIFIED_TIME_SERIES table
CREATE OR REPLACE TABLE CORE.UNIFIED_TIME_SERIES (
    DATE_COL DATE,
    YEAR INT,
    MONTH INT,
    QUARTER INT,
    FEDFUNDS_RATE FLOAT,
    RETAIL_SALES FLOAT,
    TREASURY_10Y_RATE FLOAT,
    POPULATION FLOAT,
    CPI FLOAT,
    UNEMPLOYMENT_RATE FLOAT,
    PRIMARY KEY (DATE_COL)
);

-- Populate UNIFIED_TIME_SERIES by joining DATE_SPINE and ECONOMIC_INDICATORS
INSERT INTO CORE.UNIFIED_TIME_SERIES (DATE_COL, YEAR, MONTH, QUARTER, FEDFUNDS_RATE, RETAIL_SALES, TREASURY_10Y_RATE)
SELECT
    ds.DATE_COL,
    ds.YEAR,
    ds.MONTH,
    ds.QUARTER,
    ei.FEDFUNDS_RATE,
    ei.RETAIL_SALES,
    ei.TREASURY_10Y_RATE
FROM CORE.DATE_SPINE ds
LEFT JOIN CORE.ECONOMIC_INDICATORS ei ON ds.DATE_COL = ei.DATE_COL;

-- 5. Create DATA_QUALITY_SUMMARY table
CREATE OR REPLACE TABLE CORE.DATA_QUALITY_SUMMARY (
    TABLE_NAME VARCHAR(255),
    COLUMN_NAME VARCHAR(255),
    TOTAL_ROWS INT,
    NULL_COUNT INT,
    NULL_PERCENTAGE FLOAT,
    DISTINCT_COUNT INT,
    MIN_VALUE VARIANT,
    MAX_VALUE VARIANT,
    AVG_VALUE FLOAT,
    STDDEV_VALUE FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Populate DATA_QUALITY_SUMMARY for UNIFIED_TIME_SERIES
INSERT INTO CORE.DATA_QUALITY_SUMMARY (TABLE_NAME, COLUMN_NAME, TOTAL_ROWS, NULL_COUNT, NULL_PERCENTAGE)
SELECT
    'UNIFIED_TIME_SERIES',
    'FEDFUNDS_RATE',
    COUNT(*),
    SUM(CASE WHEN FEDFUNDS_RATE IS NULL THEN 1 ELSE 0 END),
    (SUM(CASE WHEN FEDFUNDS_RATE IS NULL THEN 1 ELSE 0 END) * 100.0) / COUNT(*)
FROM CORE.UNIFIED_TIME_SERIES;

INSERT INTO CORE.DATA_QUALITY_SUMMARY (TABLE_NAME, COLUMN_NAME, TOTAL_ROWS, NULL_COUNT, NULL_PERCENTAGE)
SELECT
    'UNIFIED_TIME_SERIES',
    'RETAIL_SALES',
    COUNT(*),
    SUM(CASE WHEN RETAIL_SALES IS NULL THEN 1 ELSE 0 END),
    (SUM(CASE WHEN RETAIL_SALES IS NULL THEN 1 ELSE 0 END) * 100.0) / COUNT(*)
FROM CORE.UNIFIED_TIME_SERIES;

INSERT INTO CORE.DATA_QUALITY_SUMMARY (TABLE_NAME, COLUMN_NAME, TOTAL_ROWS, NULL_COUNT, NULL_PERCENTAGE)
SELECT
    'UNIFIED_TIME_SERIES',
    'TREASURY_10Y_RATE',
    COUNT(*),
    SUM(CASE WHEN TREASURY_10Y_RATE IS NULL THEN 1 ELSE 0 END),
    (SUM(CASE WHEN TREASURY_10Y_RATE IS NULL THEN 1 ELSE 0 END) * 100.0) / COUNT(*)
FROM CORE.UNIFIED_TIME_SERIES;
