-- =====================================================
-- PHASE 3: FEATURE ENGINEERING - SIMPLIFIED
-- Global Supply Chain Spoilage Forecasting Project
-- =====================================================

USE DATABASE GLOBAL_SPOILAGE_DB;
USE SCHEMA FEAT;

-- 1. Create ROLLING_STATS table
CREATE OR REPLACE TABLE FEAT.ROLLING_STATS AS
SELECT
    uts.DATE_COL,
    -- Rolling Means
    AVG(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS FEDFUNDS_3M_AVG,
    AVG(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS FEDFUNDS_6M_AVG,
    AVG(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS FEDFUNDS_12M_AVG,
    AVG(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS RETAIL_3M_AVG,
    AVG(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS RETAIL_6M_AVG,
    AVG(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS RETAIL_12M_AVG,
    AVG(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS TREASURY_3M_AVG,
    AVG(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TREASURY_6M_AVG,
    AVG(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TREASURY_12M_AVG,
    -- Rolling Standard Deviations
    STDDEV(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS FEDFUNDS_3M_STD,
    STDDEV(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS FEDFUNDS_6M_STD,
    STDDEV(uts.FEDFUNDS_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS FEDFUNDS_12M_STD,
    STDDEV(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS RETAIL_3M_STD,
    STDDEV(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS RETAIL_6M_STD,
    STDDEV(uts.RETAIL_SALES) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS RETAIL_12M_STD,
    STDDEV(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS TREASURY_3M_STD,
    STDDEV(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS TREASURY_6M_STD,
    STDDEV(uts.TREASURY_10Y_RATE) OVER (ORDER BY uts.DATE_COL ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS TREASURY_12M_STD
FROM CORE.UNIFIED_TIME_SERIES uts;

-- 2. Create LAG_FEATURES table
CREATE OR REPLACE TABLE FEAT.LAG_FEATURES AS
SELECT
    uts.DATE_COL,
    LAG(uts.FEDFUNDS_RATE, 1) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_LAG_1M,
    LAG(uts.FEDFUNDS_RATE, 3) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_LAG_3M,
    LAG(uts.FEDFUNDS_RATE, 6) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_LAG_6M,
    LAG(uts.FEDFUNDS_RATE, 12) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_LAG_12M,
    LAG(uts.RETAIL_SALES, 1) OVER (ORDER BY uts.DATE_COL) AS RETAIL_LAG_1M,
    LAG(uts.RETAIL_SALES, 3) OVER (ORDER BY uts.DATE_COL) AS RETAIL_LAG_3M,
    LAG(uts.RETAIL_SALES, 6) OVER (ORDER BY uts.DATE_COL) AS RETAIL_LAG_6M,
    LAG(uts.RETAIL_SALES, 12) OVER (ORDER BY uts.DATE_COL) AS RETAIL_LAG_12M,
    LAG(uts.TREASURY_10Y_RATE, 1) OVER (ORDER BY uts.DATE_COL) AS TREASURY_LAG_1M,
    LAG(uts.TREASURY_10Y_RATE, 3) OVER (ORDER BY uts.DATE_COL) AS TREASURY_LAG_3M,
    LAG(uts.TREASURY_10Y_RATE, 6) OVER (ORDER BY uts.DATE_COL) AS TREASURY_LAG_6M,
    LAG(uts.TREASURY_10Y_RATE, 12) OVER (ORDER BY uts.DATE_COL) AS TREASURY_LAG_12M
FROM CORE.UNIFIED_TIME_SERIES uts;

-- 3. Create GROWTH_FEATURES table
CREATE OR REPLACE TABLE FEAT.GROWTH_FEATURES AS
SELECT
    uts.DATE_COL,
    (uts.FEDFUNDS_RATE - LAG(uts.FEDFUNDS_RATE, 1) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.FEDFUNDS_RATE, 1) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_GROWTH_1M,
    (uts.FEDFUNDS_RATE - LAG(uts.FEDFUNDS_RATE, 12) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.FEDFUNDS_RATE, 12) OVER (ORDER BY uts.DATE_COL) AS FEDFUNDS_GROWTH_12M,
    (uts.RETAIL_SALES - LAG(uts.RETAIL_SALES, 1) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.RETAIL_SALES, 1) OVER (ORDER BY uts.DATE_COL) AS RETAIL_GROWTH_1M,
    (uts.RETAIL_SALES - LAG(uts.RETAIL_SALES, 12) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.RETAIL_SALES, 12) OVER (ORDER BY uts.DATE_COL) AS RETAIL_GROWTH_12M,
    (uts.TREASURY_10Y_RATE - LAG(uts.TREASURY_10Y_RATE, 1) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.TREASURY_10Y_RATE, 1) OVER (ORDER BY uts.DATE_COL) AS TREASURY_GROWTH_1M,
    (uts.TREASURY_10Y_RATE - LAG(uts.TREASURY_10Y_RATE, 12) OVER (ORDER BY uts.DATE_COL)) / LAG(uts.TREASURY_10Y_RATE, 12) OVER (ORDER BY uts.DATE_COL) AS TREASURY_GROWTH_12M
FROM CORE.UNIFIED_TIME_SERIES uts;

-- 4. Create VOLATILITY_FEATURES table
CREATE OR REPLACE TABLE FEAT.VOLATILITY_FEATURES AS
SELECT
    rs.DATE_COL,
    rs.FEDFUNDS_3M_STD / NULLIF(rs.FEDFUNDS_3M_AVG, 0) AS FEDFUNDS_VOLATILITY_3M,
    rs.RETAIL_3M_STD / NULLIF(rs.RETAIL_3M_AVG, 0) AS RETAIL_VOLATILITY_3M,
    rs.TREASURY_3M_STD / NULLIF(rs.TREASURY_3M_AVG, 0) AS TREASURY_VOLATILITY_3M
FROM FEAT.ROLLING_STATS rs;

-- 5. Create MASTER_FEATURES table
CREATE OR REPLACE TABLE FEAT.MASTER_FEATURES AS
SELECT
    uts.DATE_COL,
    uts.YEAR,
    uts.MONTH,
    uts.QUARTER,
    -- Original economic indicators
    uts.FEDFUNDS_RATE,
    uts.RETAIL_SALES,
    uts.TREASURY_10Y_RATE,
    uts.POPULATION,
    uts.CPI,
    uts.UNEMPLOYMENT_RATE,
    -- Rolling statistics
    rs.FEDFUNDS_3M_AVG,
    rs.FEDFUNDS_6M_AVG,
    rs.FEDFUNDS_12M_AVG,
    rs.RETAIL_3M_AVG,
    rs.RETAIL_6M_AVG,
    rs.RETAIL_12M_AVG,
    rs.TREASURY_3M_AVG,
    rs.TREASURY_6M_AVG,
    rs.TREASURY_12M_AVG,
    rs.FEDFUNDS_3M_STD,
    rs.FEDFUNDS_6M_STD,
    rs.FEDFUNDS_12M_STD,
    rs.RETAIL_3M_STD,
    rs.RETAIL_6M_STD,
    rs.RETAIL_12M_STD,
    rs.TREASURY_3M_STD,
    rs.TREASURY_6M_STD,
    rs.TREASURY_12M_STD,
    -- Lag features
    lf.FEDFUNDS_LAG_1M,
    lf.FEDFUNDS_LAG_3M,
    lf.FEDFUNDS_LAG_6M,
    lf.FEDFUNDS_LAG_12M,
    lf.RETAIL_LAG_1M,
    lf.RETAIL_LAG_3M,
    lf.RETAIL_LAG_6M,
    lf.RETAIL_LAG_12M,
    lf.TREASURY_LAG_1M,
    lf.TREASURY_LAG_3M,
    lf.TREASURY_LAG_6M,
    lf.TREASURY_LAG_12M,
    -- Growth features
    gf.FEDFUNDS_GROWTH_1M,
    gf.FEDFUNDS_GROWTH_12M,
    gf.RETAIL_GROWTH_1M,
    gf.RETAIL_GROWTH_12M,
    gf.TREASURY_GROWTH_1M,
    gf.TREASURY_GROWTH_12M,
    -- Volatility features
    vf.FEDFUNDS_VOLATILITY_3M,
    vf.RETAIL_VOLATILITY_3M,
    vf.TREASURY_VOLATILITY_3M
FROM CORE.UNIFIED_TIME_SERIES uts
LEFT JOIN FEAT.ROLLING_STATS rs ON uts.DATE_COL = rs.DATE_COL
LEFT JOIN FEAT.LAG_FEATURES lf ON uts.DATE_COL = lf.DATE_COL
LEFT JOIN FEAT.GROWTH_FEATURES gf ON uts.DATE_COL = gf.DATE_COL
LEFT JOIN FEAT.VOLATILITY_FEATURES vf ON uts.DATE_COL = vf.DATE_COL
ORDER BY uts.DATE_COL;

-- 6. Create FEATURE_AUDIT table
CREATE OR REPLACE TABLE FEAT.FEATURE_AUDIT (
    feature_name VARCHAR(255),
    feature_type VARCHAR(50),
    calculation_method VARCHAR(255),
    source_table VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Insert audit records
INSERT INTO FEAT.FEATURE_AUDIT (feature_name, feature_type, calculation_method, source_table) VALUES
('FEDFUNDS_3M_AVG', 'numeric', 'AVG over 3 months', 'CORE.UNIFIED_TIME_SERIES'),
('RETAIL_LAG_1M', 'numeric', 'LAG 1 month', 'CORE.UNIFIED_TIME_SERIES'),
('FEDFUNDS_VOLATILITY_3M', 'numeric', 'STDDEV/MEAN over 3 months', 'FEAT.ROLLING_STATS'),
('MASTER_FEATURES', 'composite', 'Join of all features', 'FEAT.MASTER_FEATURES');
