-- =====================================================
-- PHASE 9: LINEAGE & COMPLIANCE
-- Global Supply Chain Spoilage Forecasting Project
-- Access history, tags, retention, audit exports
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- =====================================================
-- 1. DATA LINEAGE TRACKING
-- =====================================================

-- Create comprehensive lineage view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.DATA_LINEAGE AS
SELECT 
    QUERY_START_TIME,
    QUERY_ID,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    DATABASE_NAME,
    SCHEMA_NAME,
    QUERY_TYPE,
    QUERY_TEXT,
    DIRECT_OBJECTS_ACCESSED,
    BASE_OBJECTS_ACCESSED,
    COLUMNS_ACCESSED,
    QUERY_TAG,
    EXECUTION_TIME,
    CREDITS_USED,
    BYTES_SCANNED,
    ROWS_PRODUCED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    AND (DATABASE_NAME = 'GLOBAL_SPOILAGE_DB' 
         OR QUERY_TEXT ILIKE '%GLOBAL_SPOILAGE%')
ORDER BY QUERY_START_TIME DESC;

-- Create data flow lineage view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.DATA_FLOW_LINEAGE AS
SELECT 
    QUERY_START_TIME,
    QUERY_ID,
    USER_NAME,
    WAREHOUSE_NAME,
    -- Extract source tables
    REGEXP_SUBSTR_ALL(DIRECT_OBJECTS_ACCESSED, '"objectName":"([^"]+)"', 1, 1, 'e', 1) AS source_tables,
    -- Extract target tables
    REGEXP_SUBSTR_ALL(BASE_OBJECTS_ACCESSED, '"objectName":"([^"]+)"', 1, 1, 'e', 1) AS target_tables,
    QUERY_TEXT,
    EXECUTION_TIME,
    CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND QUERY_TYPE IN ('INSERT', 'UPDATE', 'DELETE', 'MERGE', 'CREATE_TABLE_AS_SELECT')
    AND (DATABASE_NAME = 'GLOBAL_SPOILAGE_DB' 
         OR QUERY_TEXT ILIKE '%GLOBAL_SPOILAGE%')
ORDER BY QUERY_START_TIME DESC;

-- =====================================================
-- 2. COMPLIANCE TAGGING SYSTEM
-- =====================================================

-- Create compliance tags
CREATE OR REPLACE TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION 
    ALLOWED_VALUES 'PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED';

CREATE OR REPLACE TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS 
    ALLOWED_VALUES '7', '30', '90', '365', '2555'; -- 2555 = 7 years

CREATE OR REPLACE TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER 
    ALLOWED_VALUES 'DATA_TEAM', 'ML_TEAM', 'OPS_TEAM', 'COMPLIANCE_TEAM';

CREATE OR REPLACE TAG GLOBAL_SPOILAGE_DB.OPS.PII_FLAG 
    ALLOWED_VALUES 'YES', 'NO', 'POTENTIAL';

CREATE OR REPLACE TAG GLOBAL_SPOILAGE_DB.OPS.GDPR_APPLICABLE 
    ALLOWED_VALUES 'YES', 'NO', 'UNKNOWN';

-- =====================================================
-- 3. APPLY COMPLIANCE TAGS
-- =====================================================

-- Tag databases
ALTER DATABASE GLOBAL_SPOILAGE_DB SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'INTERNAL';
ALTER DATABASE GLOBAL_SPOILAGE_DB SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '365';
ALTER DATABASE GLOBAL_SPOILAGE_DB SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'DATA_TEAM';

-- Tag schemas
ALTER SCHEMA GLOBAL_SPOILAGE_DB.RAW SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'CONFIDENTIAL';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.RAW SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '90';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.RAW SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'DATA_TEAM';

ALTER SCHEMA GLOBAL_SPOILAGE_DB.CORE SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'INTERNAL';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.CORE SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '365';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.CORE SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'DATA_TEAM';

ALTER SCHEMA GLOBAL_SPOILAGE_DB.ML SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'INTERNAL';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.ML SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '365';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.ML SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'ML_TEAM';

ALTER SCHEMA GLOBAL_SPOILAGE_DB.OPS SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'INTERNAL';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.OPS SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '90';
ALTER SCHEMA GLOBAL_SPOILAGE_DB.OPS SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'OPS_TEAM';

-- Tag critical tables
ALTER TABLE GLOBAL_SPOILAGE_DB.ML.PREDICTIONS SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'CONFIDENTIAL';
ALTER TABLE GLOBAL_SPOILAGE_DB.ML.PREDICTIONS SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '365';
ALTER TABLE GLOBAL_SPOILAGE_DB.ML.PREDICTIONS SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'ML_TEAM';
ALTER TABLE GLOBAL_SPOILAGE_DB.ML.PREDICTIONS SET TAG GLOBAL_SPOILAGE_DB.OPS.PII_FLAG = 'NO';

ALTER TABLE GLOBAL_SPOILAGE_DB.OPS.ALERT_QUEUE SET TAG GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION = 'INTERNAL';
ALTER TABLE GLOBAL_SPOILAGE_DB.OPS.ALERT_QUEUE SET TAG GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS = '90';
ALTER TABLE GLOBAL_SPOILAGE_DB.OPS.ALERT_QUEUE SET TAG GLOBAL_SPOILAGE_DB.OPS.BUSINESS_OWNER = 'OPS_TEAM';
ALTER TABLE GLOBAL_SPOILAGE_DB.OPS.ALERT_QUEUE SET TAG GLOBAL_SPOILAGE_DB.OPS.PII_FLAG = 'NO';

-- =====================================================
-- 4. ACCESS HISTORY MONITORING
-- =====================================================

-- Create access monitoring view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.ACCESS_MONITORING AS
SELECT 
    DATE(QUERY_START_TIME) AS access_date,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    COUNT(*) AS query_count,
    SUM(CREDITS_USED) AS total_credits,
    SUM(BYTES_SCANNED) AS total_bytes_scanned,
    COUNT(DISTINCT QUERY_ID) AS unique_queries,
    MAX(QUERY_START_TIME) AS last_access_time
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    AND (DATABASE_NAME = 'GLOBAL_SPOILAGE_DB' 
         OR QUERY_TEXT ILIKE '%GLOBAL_SPOILAGE%')
GROUP BY DATE(QUERY_START_TIME), USER_NAME, ROLE_NAME, WAREHOUSE_NAME
ORDER BY access_date DESC, total_credits DESC;

-- Create suspicious activity monitoring
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.SUSPICIOUS_ACTIVITY AS
SELECT 
    QUERY_START_TIME,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    QUERY_TEXT,
    CREDITS_USED,
    BYTES_SCANNED,
    'HIGH_CREDIT_USAGE' AS activity_type,
    'User consumed ' || CREDITS_USED || ' credits in single query' AS description
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND CREDITS_USED > 10  -- High credit usage threshold
    AND (DATABASE_NAME = 'GLOBAL_SPOILAGE_DB' 
         OR QUERY_TEXT ILIKE '%GLOBAL_SPOILAGE%')

UNION ALL

SELECT 
    QUERY_START_TIME,
    USER_NAME,
    ROLE_NAME,
    WAREHOUSE_NAME,
    QUERY_TEXT,
    CREDITS_USED,
    BYTES_SCANNED,
    'UNUSUAL_ACCESS_PATTERN' AS activity_type,
    'Access outside normal hours or from unusual location' AS description
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY
WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
    AND (HOUR(QUERY_START_TIME) < 6 OR HOUR(QUERY_START_TIME) > 22)  -- Outside 6 AM - 10 PM
    AND (DATABASE_NAME = 'GLOBAL_SPOILAGE_DB' 
         OR QUERY_TEXT ILIKE '%GLOBAL_SPOILAGE%')

ORDER BY QUERY_START_TIME DESC;

-- =====================================================
-- 5. COMPLIANCE REPORTING
-- =====================================================

-- Create compliance summary view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.COMPLIANCE_SUMMARY AS
SELECT 
    CURRENT_DATE() AS report_date,
    'GLOBAL_SPOILAGE' AS project_name,
    (SELECT COUNT(*) FROM GLOBAL_SPOILAGE_DB.OPS.DATA_LINEAGE WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS queries_last_7_days,
    (SELECT COUNT(DISTINCT USER_NAME) FROM GLOBAL_SPOILAGE_DB.OPS.DATA_LINEAGE WHERE QUERY_START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())) AS unique_users_last_7_days,
    (SELECT COUNT(*) FROM GLOBAL_SPOILAGE_DB.OPS.SUSPICIOUS_ACTIVITY) AS suspicious_activities,
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES WHERE TABLE_CATALOG = 'GLOBAL_SPOILAGE_DB') AS total_tables,
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.VIEWS WHERE TABLE_CATALOG = 'GLOBAL_SPOILAGE_DB') AS total_views,
    (SELECT COUNT(*) FROM SNOWFLAKE.ACCOUNT_USAGE.SCHEMATA WHERE CATALOG_NAME = 'GLOBAL_SPOILAGE_DB') AS total_schemas;

-- =====================================================
-- 6. DATA RETENTION COMPLIANCE
-- =====================================================

-- Create retention compliance view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.RETENTION_COMPLIANCE AS
SELECT 
    TABLE_CATALOG AS database_name,
    TABLE_SCHEMA AS schema_name,
    TABLE_NAME,
    CREATED AS table_created,
    DATEDIFF('day', CREATED, CURRENT_DATE()) AS days_since_creation,
    -- Extract retention days from tags
    GET_TAG('GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS retention_days,
    CASE 
        WHEN DATEDIFF('day', CREATED, CURRENT_DATE()) > 
             CAST(GET_TAG('GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS INTEGER) 
        THEN 'OVERDUE_FOR_RETENTION'
        WHEN DATEDIFF('day', CREATED, CURRENT_DATE()) > 
             CAST(GET_TAG('GLOBAL_SPOILAGE_DB.OPS.RETENTION_DAYS', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS INTEGER) * 0.8
        THEN 'APPROACHING_RETENTION'
        ELSE 'WITHIN_RETENTION'
    END AS retention_status
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE TABLE_CATALOG = 'GLOBAL_SPOILAGE_DB'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY days_since_creation DESC;

-- =====================================================
-- 7. AUDIT EXPORT PROCEDURES
-- =====================================================

-- Procedure to export access history
CREATE OR REPLACE PROCEDURE GLOBAL_SPOILAGE_DB.OPS.SP_EXPORT_ACCESS_HISTORY(
    start_date STRING,
    end_date STRING,
    export_format STRING DEFAULT 'CSV'
)
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    export_result STRING;
    export_path STRING;
BEGIN
    -- Generate export path
    export_path := 'audit_export_' || start_date || '_to_' || end_date || '/';
    
    -- Export access history to stage
    COPY INTO @GLOBAL_SPOILAGE_DB.BACKUP.PRDBACKUP/$(export_path)access_history/
    FROM (
        SELECT *
        FROM GLOBAL_SPOILAGE_DB.OPS.DATA_LINEAGE
        WHERE DATE(QUERY_START_TIME) BETWEEN start_date AND end_date
    )
    FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP HEADER = TRUE)
    OVERWRITE = TRUE;
    
    SELECT 'ACCESS_HISTORY_EXPORTED_' || export_path INTO export_result;
    
    RETURN export_result;
END;
$$;

-- Procedure to export compliance report
CREATE OR REPLACE PROCEDURE GLOBAL_SPOILAGE_DB.OPS.SP_EXPORT_COMPLIANCE_REPORT()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    export_result STRING;
    export_path STRING;
BEGIN
    -- Generate export path
    export_path := 'compliance_report_' || TO_VARCHAR(CURRENT_DATE()) || '/';
    
    -- Export compliance summary
    COPY INTO @GLOBAL_SPOILAGE_DB.BACKUP.PRDBACKUP/$(export_path)compliance_summary/
    FROM GLOBAL_SPOILAGE_DB.OPS.COMPLIANCE_SUMMARY
    FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP HEADER = TRUE)
    OVERWRITE = TRUE;
    
    -- Export retention compliance
    COPY INTO @GLOBAL_SPOILAGE_DB.BACKUP.PRDBACKUP/$(export_path)retention_compliance/
    FROM GLOBAL_SPOILAGE_DB.OPS.RETENTION_COMPLIANCE
    FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP HEADER = TRUE)
    OVERWRITE = TRUE;
    
    -- Export suspicious activity
    COPY INTO @GLOBAL_SPOILAGE_DB.BACKUP.PRDBACKUP/$(export_path)suspicious_activity/
    FROM GLOBAL_SPOILAGE_DB.OPS.SUSPICIOUS_ACTIVITY
    FILE_FORMAT = (TYPE = CSV COMPRESSION = GZIP HEADER = TRUE)
    OVERWRITE = TRUE;
    
    SELECT 'COMPLIANCE_REPORT_EXPORTED_' || export_path INTO export_result;
    
    RETURN export_result;
END;
$$;

-- =====================================================
-- 8. COMPLIANCE ALERTING
-- =====================================================

-- Create compliance alerts table
CREATE OR REPLACE TABLE GLOBAL_SPOILAGE_DB.OPS.COMPLIANCE_ALERTS (
    alert_id STRING DEFAULT UUID_STRING(),
    alert_type STRING, -- 'RETENTION_OVERDUE', 'SUSPICIOUS_ACTIVITY', 'UNAUTHORIZED_ACCESS'
    alert_severity STRING, -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    alert_message STRING,
    affected_object STRING,
    alert_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    is_acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by STRING,
    acknowledged_at TIMESTAMP,
    resolution_notes STRING,
    PRIMARY KEY (alert_id)
);

-- =====================================================
-- 9. AUTOMATED COMPLIANCE MONITORING
-- =====================================================

-- Task for daily compliance monitoring
CREATE OR REPLACE TASK GLOBAL_SPOILAGE_DB.OPS.TASK_DAILY_COMPLIANCE_CHECK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 8 * * * UTC' -- Daily at 8 AM UTC
AS
    -- Check for overdue retention
    INSERT INTO GLOBAL_SPOILAGE_DB.OPS.COMPLIANCE_ALERTS (alert_type, alert_severity, alert_message, affected_object)
    SELECT 
        'RETENTION_OVERDUE',
        'HIGH',
        'Table ' || table_name || ' in ' || schema_name || ' is overdue for retention',
        schema_name || '.' || table_name
    FROM GLOBAL_SPOILAGE_DB.OPS.RETENTION_COMPLIANCE
    WHERE retention_status = 'OVERDUE_FOR_RETENTION';

-- Task for weekly compliance report
CREATE OR REPLACE TASK GLOBAL_SPOILAGE_DB.OPS.TASK_WEEKLY_COMPLIANCE_REPORT
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 9 * * 1 UTC' -- Weekly on Monday at 9 AM UTC
AS
    CALL GLOBAL_SPOILAGE_DB.OPS.SP_EXPORT_COMPLIANCE_REPORT();

-- =====================================================
-- 10. GDPR COMPLIANCE FEATURES
-- =====================================================

-- Create GDPR compliance view
CREATE OR REPLACE VIEW GLOBAL_SPOILAGE_DB.OPS.GDPR_COMPLIANCE AS
SELECT 
    TABLE_CATALOG AS database_name,
    TABLE_SCHEMA AS schema_name,
    TABLE_NAME,
    GET_TAG('GLOBAL_SPOILAGE_DB.OPS.PII_FLAG', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS pii_flag,
    GET_TAG('GLOBAL_SPOILAGE_DB.OPS.GDPR_APPLICABLE', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS gdpr_applicable,
    GET_TAG('GLOBAL_SPOILAGE_DB.OPS.DATA_CLASSIFICATION', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) AS data_classification,
    CASE 
        WHEN GET_TAG('GLOBAL_SPOILAGE_DB.OPS.PII_FLAG', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) = 'YES' 
        THEN 'REQUIRES_GDPR_PROTECTION'
        WHEN GET_TAG('GLOBAL_SPOILAGE_DB.OPS.PII_FLAG', TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME) = 'POTENTIAL' 
        THEN 'REVIEW_REQUIRED'
        ELSE 'NO_GDPR_CONCERNS'
    END AS gdpr_status
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES
WHERE TABLE_CATALOG = 'GLOBAL_SPOILAGE_DB'
    AND TABLE_TYPE = 'BASE TABLE'
ORDER BY gdpr_status DESC, TABLE_NAME;

-- =====================================================
-- 11. GRANT PERMISSIONS
-- =====================================================

-- Grant compliance permissions
GRANT SELECT ON ALL VIEWS IN SCHEMA GLOBAL_SPOILAGE_DB.OPS TO ROLE COMPLIANCE_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA GLOBAL_SPOILAGE_DB.OPS TO ROLE COMPLIANCE_ROLE;

GRANT USAGE ON PROCEDURE GLOBAL_SPOILAGE_DB.OPS.SP_EXPORT_ACCESS_HISTORY(STRING, STRING, STRING) TO ROLE COMPLIANCE_ROLE;
GRANT USAGE ON PROCEDURE GLOBAL_SPOILAGE_DB.OPS.SP_EXPORT_COMPLIANCE_REPORT() TO ROLE COMPLIANCE_ROLE;

-- Grant task permissions
GRANT EXECUTE TASK ON ACCOUNT TO ROLE OPS_TASK_ROLE;

-- =====================================================
-- 12. AUDIT LOG
-- =====================================================

INSERT INTO GLOBAL_SPOILAGE_DB.OPS.LOAD_AUDIT (
    execution_id, phase, step, execution_ts, status, rows_affected, execution_time_seconds, error_message
) VALUES (
    'PHASE9_COMPLIANCE_' || CURRENT_TIMESTAMP()::STRING,
    'PHASE_9',
    'LINEAGE_COMPLIANCE_SETUP',
    CURRENT_TIMESTAMP(),
    'SUCCESS',
    0,
    0,
    NULL
);

-- Success message
SELECT 'Phase 9: Lineage & Compliance setup completed successfully!' AS status;
